#!/bin/bash 
NAME="wlan0" #interface always up
RATE="20kbps"

if [ -n "$1" ]
then
  if [ $1 = 'u' ]; then
    tc qdisc del dev $NAME root
  elif [ $1 = 'l' ]; then 
    tc qdisc add dev $NAME root netem rate $RATE
  else
    echo "Not valid"
  fi
  exit  
fi



