#!/bin/bash 
NAME="eth0"
#NAME="enp2s0"

SERVER="132.227.62.164/32"

main() {
    COMM="rate 1Mbit delay 60ms 6ms loss 1%"
    setRateTime "$COMM" 5
    
    COMM="rate 1Mbit delay 15ms 2ms loss 1%"
    setRateTime "$COMM" 5

    COMM="rate 1Mbit delay 100ms 10ms loss 1%"
    setRateTime "$COMM" 5

    COMM="rate 1Mbit delay 80ms 7ms loss 1%"
    setRateTime "$COMM" 5

    COMM="rate 1Mbit delay 15ms 2ms loss 1%"
    setRateTime "$COMM" 5

    COMM="rate 1Mbit delay 30ms 4ms loss 1%"
    setRateTime "$COMM" 5
}

################################# 
TYPE="add"

function resetNetem {
    tc qdisc del dev $NAME root
    tc qdisc del dev ifb0 root 
    
    tc qdisc add dev $NAME root handle 1: prio
    tc qdisc add dev ifb0 root handle 1: prio

    echo "Reset interface"
}

function setRateTime { # $1 rate command $2 sleep time

    if [ $TYPE = 'add' ] 
    then
      addRate "$1"
    else
      changeRate "$1"
    fi

    echo $1
    sleep $2
}

function addRate {
    tc qdisc add dev $NAME parent 1:3 handle 30: netem $1
    if [ $? -eq '0' ] 
    then
      tc filter add dev $NAME protocol ip parent 1:0 prio 3 u32 match ip protocol 17 0xff match ip dport 6363 0xffff match ip dst $SERVER flowid 1:3
      tc qdisc add dev ifb0 parent 1:3 handle 30: netem $1
      tc filter add dev ifb0 protocol ip parent 1:0 prio 3 u32 match ip protocol 17 0xff match ip dport 6373 0xffff match ip src $SERVER flowid 1:3
    else
      changeRate "$1"
    fi
    
    TYPE="change"
}

function changeRate {
    tc qdisc change dev $NAME parent 1:3 handle 30: netem $1
    tc qdisc change dev ifb0 parent 1:3 handle 30: netem $1
}

function setInterfaceDown { # $1 time down

    ip link set $NAME down
    ip link set ifb0 down

    echo "Interface down"

    sleep $1

    ip link set $NAME up
    ip link set ifb0 up

    echo "Interface up"

}

function load {
  modprobe ifb
  ip link set dev ifb0 up
  tc qdisc add dev $NAME ingress
  tc filter add dev $NAME parent ffff: protocol ip u32 match u32 0 0 flowid 1:1 action mirred egress redirect dev ifb0

  resetNetem
}

function unload {
  sudo modprobe -r ifb
  tc qdisc del dev $NAME ingress
  tc qdisc del dev $NAME root
}

if [ -n "$1" ]
then
  if [ $1 = 'u' ] 
  then
    unload
  elif [ $1 = 'l' ] 
  then 
    load
  elif [ $1 = 'r' ] 
  then
    resetNetem
  fi
  exit  
fi

main "$@"

