#!/bin/bash 
NAME="eth0"
#NAME="enp2s0"

main() {
    SPEED="1000kbit buffer 50000 limit 10000"
    COMM="delay 40ms 4ms loss 7%"

    setRateDelaySleep "$SPEED" "$COMM" 3


    SPEED="500kbit buffer 50000 limit 10000"
    COMM="delay 50ms 4ms loss 10%"

    setRateDelaySleep "$SPEED" "$COMM" 3


    setInterfaceDown 25


    SPEED="1000kbit buffer 50000 limit 10000"
    COMM="delay 30ms 2ms loss 1%"

    setRateDelaySleep "$SPEED" "$COMM" 6


    resetNetem
}

#################################

function resetNetem {
    tc qdisc del dev $NAME root
    tc qdisc del dev ifb0 root 

    echo "Reset interface"
}

function setRate { # $1 rate command
    tc qdisc add dev $NAME root handle 1:0 tbf rate $1
    tc qdisc add dev ifb0 root handle 1:0 tbf rate $1 

    echo $1
}

function setDelay { # $1 delay command
    tc qdisc add dev $NAME parent 1:0 handle 10: netem $1
    tc qdisc add dev ifb0 parent 1:0 handle 10: netem $1

    echo $1
}

function setRateDelaySleep { # $1 rate command  $2 delay command  $3 sleep time
    resetNetem

    setRate "$1"
    setDelay "$2"

    sleep $3
}

function setInterfaceDown { # $1 time down

    ip link set $NAME down
    ip link set ifb0 down

    echo "Interface down"

    sleep $1

    ip link set $NAME up
    ip link set ifb0 up

    echo "Interface up"

}

main "$@"

